# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking account'), ('savings', 'Savings account'), ('investment', 'Investment account'), ('secondparty', 'Second party account'), ('other', 'Other account')], default='other', max_length=10),
        ),
    ]
